# this file contains the default config, which is what's used for rohangodha.com/Resume.pdf

includeLocation = false

projects = ["attendance", "alphasnake", "ecoflare"]

twentysix = false

ats = true
