interests = [
  "Overwatch (2x national champion)",
  "Rap and Hip-Hop music (JID, Kendrick Lamar)",
]

[personal]
name = "Rohan Godha"
title = "FULLSTACK ENGINEER"
website = "rohangodha.com"
github = "github.com/rgodha24"
email = "rgodha3@gatech.edu"
linkedin = "linkedin.com/in/rohan-godha"
location = "Scottsdale, AZ"

[[work]]
organization = "NewGen Business Solutions"
url = "newgennow.com/"
position = "Intern"
startDate = "2023-05-01"
endDate = "2023-08-01"
highlights = [
  "Modernized Oracle’s SuiteCloud Extension testing framework by migrating outdated Jest version to Vitest",
  "Created tests for 80% of all API endpoints in ConventionSuite, NewGen’s primary product, increasing confidence in their ongoing rewrite from Create-React-App to Vite",
  "Led effort to modernize target client database, increasing conversion rate on email marketing campaigns",
]

[[education]]
institution = "Georgia Institute of Technology, College of Computing"
url = "gatech.edu"
area = "Computer Science"
studyType = "Candidate: B.S."
concentrations = ["Devices", "Intelligence"]
startDate = "2024-08-01"
endDate = "2027-05-01"
honors = []
courses = ["Data Structures & Algorithms", "Linear Algebra"]
highlights = [
  "*Activities*: Marine Robotics Group, dependently-typed, Competitive Programming",
]

[[education]]
institution = "Brophy College Preparatory"
url = "brophyprep.org"
area = ""
studyType = ""
concentrations = []
startDate = "2020-08-01"
endDate = "2024-05-01"
honors = []
courses = [
  "Intro to Engineering",
  "Advanced Innovative Technology",
  "GPA: 4.519/4.0",
]
highlights = [
  "*Activities*: Broncobotics, Coding Club, National Honors Society, Brophy Big Brothers",
]


[[affiliations]]
organization = "Broncobotics"
position = "Head of Technology"
url = "broncobotics.org"
startDate = "2020-08-30"
endDate = "2024-05-30"
highlights = [
  "Created virtual courses to teach over 70 students CAD, Programming, Project Management, and Machining",
  "Led team to second place finish in the Las Vegas FRC Regional in 2022 as programmer and strategist",
  "Spearheaded 20 student team creating and coding a robot in 6 weeks for the FIRST Robotics Competition",
]

[[affiliations]]
organization = "Marine Robotics Group"
position = "Member"
url = "marinerobotics.gtorg.gatech.edu/"
startDate = "2024-08-01"
endDate = "present"
highlights = [
  "Updated internal documentation in the RobotX competition repository to make onboarding simpler",
  "Created a web-based dashboard to display telemetry data from the autonomous boat and UAV",
]

[[skills]]
category = "Programming Languages"
skills = ["Javascript/Typescript", "Rust", "Python", "Java", "Go", "Nix"]


[[skills]]
category = "Web Development"
skills = [
  "React",
  "Next.js",
  "Svelte",
  "Tailwind CSS",
  "AWS",
  "Serverless",
  "IAC",
  "Cloudflare Pages",
]

[[languages]]
language = "English"
fluency = "Native speaker"

[[languages]]
language = "Hindi"
fluency = "Conversational"

[[languages]]
language = "Spanish"
fluency = "Basic proficiency"
