[personal]
name = "Rohan Godha"
title = "FULLSTACK ENGINEER"
website = "rohangodha.com"
github = "github.com/rgodha24"
email = "rgodha3@gatech.edu"
linkedin = "linkedin.com/in/rohan-godha"
instagram = "instagram.com/aws_peter"
location = "Scottsdale, AZ"

[[work]]
organization = "Pump (YC S22)"
url = "pump.co/"
position = "Technical Content & Social Media Lead"
location = "Atlanta, GA"
startDate = "2025-08-25"
endDate = "present"
highlights = [
  "Generated 150k+ views per week on TikTok and Instagram through technical tutorials on AWS",
  "Leading marketing team to grow Pump's inbound sales for their AWS cost optimization program",
]

[[work]]
organization = "Rocketlab"
url = "rocketlabusa.com/"
position = "Software Engineering Intern"
location = "Albuquerque, NM"
startDate = "2025-05-12"
endDate = "2025-08-01"
highlights = [
  "Replaced manual solar panel validation process with Python based simulation, achieving large speedup through 16-way parallel processing on Kubernetes with RabbitMQ/KEDA auto-scaling",
  "Improved loadtime of critical factory visualizations by 192x through optimizing PostgreSQL queries",
  "Unified priority lot tracking with factory visualization, improving visibility of high-value products",
  "Built terminal-based Jira interface, increasing ticket throughput and improving managerial visibility",
]

[[work]]
organization = "Brainrot dot mov"
url = "brainrot.mov"
position = "Founder"
location = "Atlanta, GA"
startDate = "2025-02-17"
endDate = "present"
highlights = [
  "Developed distributed video generation platform using React, TypeScript and AWS Lambda, enabling users to create viral short-form content with AI Voices",
  "Proved product-market fit by growing my #link(\"https://instagram.com/aws_peter\")[\\@aws_peter] account to 70k+ followers and 4.7M+ views across Instagram, TikTok and YouTube, producing technical tutorials on Docker, AWS, MCP and AI Agents",
  "Grew SaaS to >\\$1k MRR by enabling 1500+ creators to generate 25M+ views and 200k+ followers",
]

[[work]]
organization = "Georgia Tech Bits of Good"
position = "Engineering Manager"
url = "https://bitsofgood.org/"
location = "Atlanta, GA"
startDate = "2025-01-20"
endDate = "present"
highlights = [
  "Leading team of 5 developers to create application to encourage children to take their medicine",
  "Created internal CLI based on shadcn/ui for easy access to design system for all Bits of Good projects",
]

[[work]]
organization = "Unstoppable Asset"
url = "https://unstoppableasset.com"
position = "Co-Founder"
location = "Atlanta, GA"
startDate = "2023-07-01"
endDate = "present"
highlights = [
  "Leading product development for a mission driven fintech startup selected for Create-X S'25 Batch",
]

[[work]]
organization = "NewGen Business Solutions"
url = "newgennow.com/"
position = "Intern"
location = "Scottsdale, AZ"
startDate = "2023-05-01"
endDate = "2023-08-01"
highlights = [
  "Developed a testing framework for critical application during migration from Create-React-App to Vite",
]

[[education]]
institution = "Georgia Institute of Technology"
url = "gatech.edu"
area = "Computer Science"
studyType = "Candidate: B.S."
concentrations = ["Information Networks", "System Architecture"]
startDate = "2024-08-01"
endDate = "2027-05-01"
honors = []
courses = [
  "Database Systems",
  "Computer Organization",
  "Systems and Networks",
  "Data Structures & Algorithms",
  "Design & Analysis of Algorithms",
]
highlights = []

[[skills]]
category = "Programming Languages"
skills = ["Typescript", "Rust", "Go", "Nix", "Python", "HTML/CSS/Javascript"]

[[skills]]
category = "Frameworks & Technologies"
skills = [
  "Svelte/Sveltekit",
  "React",
  "Next.js",
  "Tanstack Start",
  "Tailwind CSS",
  "AWS",
  "Infrastructure as Code (IaC)",
  "Docker",
]
