[personal]
name = "Rohan Godha"
title = "FULLSTACK ENGINEER"
website = "rohangodha.com"
github = "github.com/rgodha24"
email = "rgodha3@gatech.edu"
linkedin = "linkedin.com/in/rohan-godha"
instagram = "instagram.com/aws_peter"
location = "Scottsdale, AZ"

[[work]]
organization = "Rocketlab"
url = "rocketlabusa.com/"
position = "Web Software Engineering Intern"
startDate = "2025-05-12"
endDate = "present"
highlights = [
  "Integrated realtime factory visualization with 'HotLots', delivering observability on critical production areas",
  "Optimized speed of semiconductor calibration through predictive modeling of positions and temperatures",
  "Reduced hotpath query latency from 10s to 20ms by optimizing PostgreSQL on Kubernetes infrastructure",
  "Developed terminal-based Jira interface, increasing ticket throughput and improving managerial visibility",
]

[[work]]
organization = "Brainrot.mov"
url = "https://brainrot.mov"
position = "Founder"
startDate = "2025-02-17"
endDate = "present"
highlights = [
  "Grew an educational developer focused account #link(\"https://instagram.com/aws_peter\")[(\\@aws_peter)] to 70k+ followers, 4.5M+ views, and 1.6M unique viewers by teaching concepts like Docker, Kubernetes, AWS Lambda, and Infrastructure as Code",
  "Created a Fullstack React app for generating short form videos using AI voices, with over 300 unique AWS Resources, 10s of gigabytes of user data stored on S3, deployed and managed using Infrastructure as Code.",
  "Enabled 1500+ users to generate over 25 million views and 200 thousand followers with over \\$1k in revenue.",
]

[[work]]
organization = "NewGen Business Solutions"
url = "newgennow.com/"
position = "Software Engineering Intern"
startDate = "2023-05-01"
endDate = "2023-08-01"
highlights = [
  "Created tests for 80% of all API endpoints in ConventionSuite, NewGen’s primary product, increasing confidence in their ongoing rewrite from Create-React-App to Vite",
]

[[education]]
institution = "Georgia Institute of Technology, College of Computing"
url = "gatech.edu"
area = "Computer Science"
studyType = "Candidate: B.S."
concentrations = ["Devices", "System Architecture"]
startDate = "2024-08-01"
endDate = "2027-05-01"
honors = []
courses = [
  "Data Structures & Algorithms",
  "Linear Algebra",
  "Objects and Design",
  "Computer Organization",
]
highlights = [
  "*Activities*: GT Bits of Good, dependently-typed, Competitive Programming",
]

[[affiliations]]
organization = "Georgia Tech Bits of Good"
position = "Engineering Manager"
url = "https://bitsofgood.org/"
startDate = "2025-01-20"
endDate = "present"
highlights = [
  "Implemented a new design system directly from Figma using React, Radix UI, TailwindCSS and Next.js",
  "Created an internal CLI tool based on shadcn/ui for easy access to design system for all Bits of Good projects",
]

[[affiliations]]
organization = "Broncobotics"
position = "Head of Technology"
url = "broncobotics.org"
startDate = "2020-08-30"
endDate = "2024-05-30"
highlights = [
  "Led team to second place finish in the Las Vegas FRC Regional in 2022 as programmer and strategist",
  "Spearheaded 20 student team creating and coding a robot in 6 weeks for the FIRST Robotics Competition",
]


[[skills]]
category = "Programming Languages"
skills = ["Typescript", "Rust", "Go", "Nix"]


[[skills]]
category = "Frameworks & Technologies"
skills = [
  "React",
  "Next.js",
  "Svelte",
  "Tailwind CSS",
  "AWS",
  "Infrastructure as Code",
  "Docker",
]

[[languages]]
language = "English"
fluency = "Native speaker"

[[languages]]
language = "Hindi"
fluency = "Conversational"

[[languages]]
language = "Spanish"
fluency = "Basic proficiency"
