[personal]
name = "Rohan Godha"
title = "FULLSTACK ENGINEER"
website = "rohangodha.com"
github = "github.com/rgodha24"
email = "rgodha3@gatech.edu"
linkedin = "linkedin.com/in/rohan-godha"
instagram = "instagram.com/aws_peter"
location = "Scottsdale, AZ"

[[work]]
organization = "Pump (YC S22)"
url = "pump.co/"
position = "Incoming Growth & Social Media"
startDate = "2025-08-25"
endDate = "present"
highlights = []

[[work]]
organization = "Rocketlab"
url = "rocketlabusa.com/"
position = "Software Engineering Intern"
startDate = "2025-05-12"
endDate = "2025-08-01"
highlights = [
  "Replaced manual solar panel validation process with Python based simulation, achieving large speedup through 16-way parallel processing on Kubernetes with RabbitMQ/KEDA auto-scaling",
  "Improved loadtime of critical factory visualizations by 192x through optimizing PostgreSQL queries",
  "Unified priority lot tracking with factory visualization, improving visibility of high-value products",
  "Built terminal-based Jira interface, increasing ticket throughput and improving managerial visibility",
]

[[work]]
organization = "Brainrot.mov"
url = "https://brainrot.mov"
position = "Founder"
startDate = "2025-02-17"
endDate = "present"
highlights = [
  "Developed distributed video generation platform using React, TypeScript and AWS Lambda, enabling users to create viral short-form content with AI Voices",
  "Proved product-market fit by growing my #link(\"https://instagram.com/aws_peter\")[\\@aws_peter] account to 70k+ followers and 4.7M+ views across Instagram, TikTok and YouTube, producing technical tutorials on Docker, AWS, MCP and AI Agents",
  "Launched as SaaS product enabling 1500+ creators to generate 25M+ views and 200k+ followers, with thousands in revenue",
]

[[work]]
organization = "Unstoppable Asset"
url = "https://unstoppableasset.com"
position = "Co-Founder"
startDate = "2023-07-01"
endDate = "present"
highlights = [
  "Leading product development for a mission driven fintech startup selected for Create-X S'25 Batch",
]

[[work]]
organization = "NewGen Business Solutions"
url = "newgennow.com/"
position = "Intern"
startDate = "2023-05-01"
endDate = "2023-08-01"
highlights = []

[[education]]
institution = "Georgia Institute of Technology, College of Computing"
url = "gatech.edu"
area = "Computer Science"
studyType = "Candidate: B.S."
concentrations = ["Information Networks", "System Architecture"]
startDate = "2024-08-01"
endDate = "2027-05-01"
honors = []
courses = [
  "Data Structures & Algorithms",
  "Objects & Design",
  "Computer Organization",
]
highlights = []

[[affiliations]]
organization = "Georgia Tech Bits of Good"
position = "Engineering Manager"
url = "https://bitsofgood.org/"
startDate = "2025-01-20"
endDate = "present"
highlights = [
  "Implemented a new design system directly from Figma using React, Radix UI, TailwindCSS and Next.js",
  "Created internal CLI based on shadcn/ui for easy access to design system for all Bits of Good projects",
]

[[skills]]
category = "Programming Languages"
skills = ["Typescript", "Rust", "Go", "Nix"]


[[skills]]
category = "Frameworks & Technologies"
skills = [
  "React",
  "Next.js",
  "Svelte",
  "Tailwind CSS",
  "AWS",
  "Infrastructure as Code",
  "Docker",
]
