[personal]
name = "Rohan Godha"
title = "FULLSTACK ENGINEER"
website = "rohangodha.com"
github = "github.com/rgodha24"
email = "rgodha3@gatech.edu"
linkedin = "linkedin.com/in/rohan-godha"
instagram = "instagram.com/aws_peter"
location = "Scottsdale, AZ"

[[work]]
organization = "Mintlify"
url = "mintlify.com/"
position = "Incoming Software Engineering Intern"
location = "San Francisco, CA"
startDate = "2026-05-12"
endDate = "2026-08-01"
highlights = []

[[work]]
organization = "Rocketlab"
url = "rocketlabusa.com/"
position = "Software Engineering Intern"
location = "Albuquerque, NM"
startDate = "2025-05-12"
endDate = "2025-08-01"
highlights = [
  "Replaced manual solar panel validation process with Python based simulation, achieving large speedup through 16-way parallel processing on Kubernetes with RabbitMQ/KEDA auto-scaling",
  "Improved loadtime of critical factory visualizations by 192x through optimizing PostgreSQL queries",
  "Unified priority lot tracking with factory visualization, improving visibility of high-value products",
  "Built terminal-based Jira interface, increasing ticket throughput and improving managerial visibility",
]

[[work]]
organization = "AI UGC Startup"
url = "brainrot.mov"
position = "Founder (acquired)"
location = "Atlanta, GA"
startDate = "2025-02-17"
endDate = "2025-12-01"
highlights = [
  "Developed distributed video generation platform using React, TypeScript and AWS Lambda, enabling users to create viral short-form content with AI Voices",
  "Proved product-market fit by growing my [@aws_peter](https://instagram.com/aws_peter) account to 70k+ followers and 4.7M+ views across Instagram, TikTok and YouTube, producing technical tutorials on Docker, AWS, MCP and AI Agents",
  "Grew SaaS to >$1k MRR by enabling 1500+ creators to generate 25M+ views and 200k+ followers",
]

[[work]]
organization = "Unstoppable Asset"
url = "unstoppableasset.com"
position = "Co-Founder"
location = "Atlanta, GA"
startDate = "2023-07-01"
endDate = "2025-08-01"
highlights = [
  "Leading product development for a mission driven fintech startup selected for Create-X S'25 Batch",
]

[[work]]
organization = "NewGen Business Solutions"
url = "newgennow.com/"
position = "Intern"
location = "Scottsdale, AZ"
startDate = "2023-05-01"
endDate = "2023-08-01"
highlights = [
  "Developed a testing framework for critical application during migration from Create-React-App to Vite",
]

[[education]]
institution = "Georgia Institute of Technology"
url = "gatech.edu"
area = "Computer Science"
studyType = "Candidate: B.S."
concentrations = ["Information Networks", "System Architecture"]
startDate = "2024-08-01"
endDate = "2027-05-01"
honors = []
courses = [
  "Database Systems",
  "Computer Organization",
  "Systems and Networks",
  "Data Structures & Algorithms",
  "Design & Analysis of Algorithms",
]
highlights = [
  "*Leadership*: Engineering Manager, GT Bits of Good: managing 10+ developers on nonprofit websites",
]

[[skills]]
category = "Programming Languages"
skills = ["Typescript", "Rust", "Go", "Nix", "Python", "HTML/CSS/Javascript"]

[[skills]]
category = "Frameworks & Technologies"
skills = [
  "Svelte/Sveltekit",
  "React",
  "Next.js",
  "Tanstack Start",
  "Tailwind CSS",
  "AWS",
  "Infrastructure as Code (IaC)",
  "Docker",
  "ray",
  "pytorch",
  "CUDA",
  "SLURM",
]
