interests = ["Video Games", "Reading Science Fiction", "Rap and Hip-Hop music"]

[personal]
name = "Rohan Godha"
title = "FULLSTACK ENGINEER"
website = "rohangodha.com"
github = "github.com/rgodha24"
email = "rgodha3@gatech.edu"
linkedin = "linkedin.com/in/rohan-godha"

[[work]]
organization = "NewGen Business Solutions"
url = "https://newgennow.com/"
position = "Intern"
startDate = "2023-05-01"
endDate = "2023-08-01"
highlights = [
  "Modernized Oracle’s SuiteCloud Extension testing framework by migrating from Jest version to Vitest",
  "Created tests for 80% of all API endpoints in ConventionSuite, NewGen’s primary product, increasing confidence in their ongoing rewrite from Create-React-App to Vite",
  "Led effort to modernize target client database, increasing conversion rate on email marketing campaigns",
]

[[education]]
institution = "Georgia Institute of Technology, College of Computing"
url = "https://example.com/"
area = "Computer Science"
studyType = "Candidate: B.S."
concentrations = ["Devices", "Intelligence"]
startDate = "2024-08-01"
endDate = "2027-05-01"
honors = []
courses = ["Data Structures & Algorithms", "Linear Algebra"]
highlights = [
  "*Activities*: Marine Robotics Group, dependently-types, Competitive Programming",
]

[[education]]
institution = "Brophy College Preparatory"
url = "https://brophyprep.org"
area = ""
studyType = ""
concentrations = []
startDate = "2020-08-01"
endDate = "2024-05-01"
honors = []
courses = [
  "Intro to Engineering",
  "Advanced Innovative Technology",
  "GPA: 4.519/4.0",
]
highlights = [
  "*Activities*: Broncobotics, Coding Club, National Honors Society, Brophy Big Brothers",
]


[[affiliations]]
organization = "Broncobotics"
position = "Head of Technology"
url = "https://broncobotics.org"
startDate = "2020-08-30"
endDate = "2024-05-30"
highlights = [
  "Created virtual courses to teach over 70 students CAD, Programming, Project Management, and Machining",
  "Led team to second place finish in the Las Vegas FRC Regional in 2022 as programmer and strategist",
  "Spearheaded 20 student team creating and coding a robot in 6 weeks for the FIRST Robotics Competition",
]

[[affiliations]]
organization = "Marine Robotics Group"
position = "Member"
url = "https://marinerobotics.gtorg.gatech.edu/"
startDate = "2024-08-01"
endDate = "present"
highlights = [
  "Updated internal documentation in the RobotX competition repository to make onboarding simpler",
  "Created a web-based dashboard to display telemetry data from the autonomous boat and UAV",
]

[[projects]]
name = "Brophy Attendance"
url = "rgodha.com/attendance"
highlights = [
  "Built an attendance system in use at Brophy College Prep based on scanning barcodes on student ids",
  "Created and integrated a Raspberry Pi-based barcode scanner in Rust, an AWS Lambda based backend in Typescript, and a realtime, local-first, web dashboard in Typescript using technology like SST and React",
]

[[projects]]
name = "Portfolio"
url = "rgodha.com/portfolio"
highlights = [
  "Utilized SolidJS and Astro to create a unique portfolio website based around animated text and canvases",
  "Built a resume generator using typst to create a resume from a TOML file and display it on the website",
]

[[projects]]
name = "Advent of Code"
url = "rgodha.com/aoc"
highlights = [
  "Solutions for the competitive programming challenge Advent of Code, in Rust, Python and Typescript",
  "Used Advent of Code to teach 30+ students programming as President of the Coding Club",
]

[[projects]]
name = "cryptenv"
url = "rgodha.com/cryptenv"
highlights = [
  "Developed a tool to store encrypted environment variables, and switch between them for different projects",
]

[[skills]]
category = "Programming Languages"
skills = ["Typescript", "Rust", "Python", "Java", "Go"]


[[skills]]
category = "Web Development"
skills = [
  "React",
  "Next.js",
  "Svelte & Sveltekit",
  "Tailwind CSS",
  "AWS",
  "Cloudflare Pages",
]

[[languages]]
language = "English"
fluency = "Native speaker"

[[languages]]
language = "Hindi"
fluency = "Conversational"

[[languages]]
language = "Spanish"
fluency = "Basic proficiency"
