[aoc]
title = "Advent of Code"
blurb = "Competitive Programming Competition Advent of Code"
order = 25
tech = ["Typescript", "Rust", "Python"]
bullets = [
  "Solved Advent of Code in multiple Rust, Python, and Typescript with full completion in 2024 and Rust",
  "Taught 30+ students programming through AOC as Coding Club President at Brophy College Prep",
]

github = "rgodha24/advent-of-code"

[attendance]
title = "Brophy Attendance"
blurb = "A realtime and localfirst attendance system in use at Brophy College Preparatory"
order = 80
tech = ["sst", "AWS", "shadcn/ui", "React", "Rust", "ElectroDB", "Typescript"]
bullets = [
  "Built an attendance system in use at Brophy College Prep based on scanning barcodes on student ids",
  "Created and integrated a Raspberry Pi-based barcode scanner in Rust, an AWS Lambda based backend in Typescript, and a realtime, local-first, web dashboard in Typescript using technology like SST and React",
]

website = "https://batt.rgodha.com"
github = "rgodha24/attendance"

[cryptenv]
title = "Cryptenv"
blurb = "An environment variable manager that switches envs per project, built in Rust"
order = 20
tech = ["Rust"]
bullets = [
  "A Rust-based tool to store encrypted environment variables, and switch between them for different projects",
]

github = "rgodha24/cryptenv"

[portfolio]
title = "Portfolio"
blurb = "An Astro powered portfolio website and a typst built Resume using the same data"
order = 50
tech = ["Astro", "Typst", "UnoCSS", "Cloudflare Pages"]
bullets = [
  "Utilized SolidJS and Astro to create a unique portfolio website based around animated text and canvases",
  "Built a resume generator using typst to create a resume from a TOML file and display it on the website",
]

website = "https://rohangodha.com"
github = "rgodha24/portfolio"

[lockinai]
title = "LockIn AI"
blurb = "A website and application combo to keep students focused on their laptop"
order = 30
tech = ["AWS", "Typescript", "Swift", "Tensorflow", "React", "Websockets"]
bullets = [
  "Built a serverless realtime backend on AWS using SST, Typescript, and AWS Websocket API Gateway",
  "Integrated Tensorflow Mediapipe face tracking model into a React frontend using Zustand state manager",
]

github = "sailalithkanumuri8/LockInAI"
website = "https://lockinai.rohangodha.com/"
devpost = "https://devpost.com/software/lockin-ai"

[teachtok]
title = "TeachTok"
blurb = "Upload your notes and learn using a TikTok like interface!"
order = 25
tech = [
  "AWS",
  "Typescript",
  "React Native",
  "Claude",
  "OCR",
  "MongoDB",
  "Infrastructure as Code",
]
bullets = [
  "Built an infintely scalable serverless backend using AWS Lambda, AWS SQS, AWS S3 and Claude API",
  "Created a React Native mobile application with image uploading and scrolling capabilities",
]

github = "RayanDas06/QuizAI"
devpost = "https://devpost.com/software/teachtok"
